//
// Run Parsnp and ReporTree using all assemblies in database
//

/*
=============================================================================================================================
    SUBWORKFLOW FUNCTIONS
=============================================================================================================================
*/

//Function to get all the previous assembly files for each species
def get_previous_assemblies(species ) {
    // Create the path to get the previous fasta files
    def previous_assemblies = file("${params.outdir}/${species}/assemblies/*.{fasta,fa,fas,fna}")
    return previous_assemblies
}

//Function to return the previous HC partitions table or empty list
def get_previous_partitions_tsv(species) {
    def p = "${params.outdir}/${species}/ReporTree/${species}_partitions.tsv"
    return new File(p).exists() ? file(p) : []
}

/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    IMPORT LOCAL MODULES
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/
include { PARSNP                                   } from '../../modules/local/parsnp/parsnp.nf'
include { CLEAN_FASTA                              } from '../../modules/local/parsnp/clean_fasta.nf'
include { CONVERT_XMFA_FASTA                       } from '../../modules/local/parsnp/convert_xmfa_fasta.nf'
include { IQTREE as IQTREE_PARSNP                  } from '../../modules/local/tree/iqtree.nf'
include { CONSTANTSITES as CONSTANT_SITES_PARSNP   } from '../../modules/local/tree/constant_sites.nf'
include { ROOT_TREE as ROOT_TREE_PARSNP            } from '../../modules/local/tree/root_tree.nf'
include { REPORTREE_PARSNP                         } from '../../modules/local/reportree/reportree_parsnp.nf'
include { CHECK_METADATA_MSA                       } from '../../modules/local/reportree/check_metadata_msa.nf'

/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    RUN MAIN SUBWORKFLOW
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/
workflow PARSNP_ANALYSIS {

    take:
    ch_samples          // channel: [ val(meta), assembly ]
    ch_parsnp_species   // channel: [[species,count]] //counts included the latest assemblies
 
    main:

    ch_versions = Channel.empty()

    //For each species get the previous fasta files
    ch_previous_assemblies = Channel.empty()
    ch_previous_assemblies = ch_previous_assemblies.mix(
        ch_parsnp_species.map{
            meta -> [[species:meta[0].species],get_previous_assemblies(meta[0].species)]
        }
    )

    //Group all the samples by species
    ch_samples.map{
        meta, assembly -> [[species:meta.species],assembly]
    }
    .groupTuple()
    .set{ch_samples_grouped_species}
    //
    // Join the new assemblies and the old assemblies
    //
    ch_all_assemblies = ch_samples_grouped_species.join(ch_previous_assemblies)
        .map{meta,new_assemblies, old_assemblies -> [meta,new_assemblies+old_assemblies]}

    // If samples are reran, may cause occasional duplicates from inputs and old_assemblies
    //Deduplicate possible assemblies
    ch_deduplicated_assemblies = ch_all_assemblies
        .map{
            meta, files ->
            //Convert to File objects in case they're strings
            def file_objects = files.collect{
                it instanceof String ? file(it) : it
            }
            //Deduplicate by basename - keep first occurence of each basename
            def unique_files_map = [:]
            file_objects.each { file ->
                def basename = file.name
                if (!unique_files_map.containsKey(basename)){
                    unique_files_map[basename] = file
                }
            }
            return [meta, unique_files_map.values()]
        }
    //
    // MODULE: Run Parsnp on each unique species
    //
    PARSNP(
        ch_deduplicated_assemblies
    )
    ch_versions = ch_versions.mix(PARSNP.out.versions)
    //
    // MODULE: Clean multi fasta generated by PARSNP
    //
    CLEAN_FASTA(
        PARSNP.out.snps_alignment
    )
    ch_versions = ch_versions.mix(CLEAN_FASTA.out.versions)
    //
    // MODULE: If a phylogenetic tree is required generate an ML tree based on SNPs with adjusted branch length
    //
    ch_snp_tree = Channel.empty()
    if(params.tree) {
        CONVERT_XMFA_FASTA(PARSNP.out.xmfa)
        ch_versions = ch_versions.mix(CONVERT_XMFA_FASTA.out.versions)
        
        CONSTANT_SITES_PARSNP(CONVERT_XMFA_FASTA.out.core_aln)
        ch_versions = ch_versions.mix(CONSTANT_SITES_PARSNP.out.versions)

        const_ch = CONSTANT_SITES_PARSNP.out.constant_sites.map { meta, p -> tuple(meta, p.text.trim())}

        iqtree_input = CLEAN_FASTA.out.cleaned_snps_alignment
            .join(const_ch)
            .map { meta, msa, const_sites ->
                tuple(meta, msa, const_sites)
            }
        IQTREE_PARSNP(iqtree_input)
        ch_versions = ch_versions.mix(IQTREE_PARSNP.out.versions)

        ROOT_TREE_PARSNP(IQTREE_PARSNP.out.phylogeny)
        ch_versions = ch_versions.mix(ROOT_TREE_PARSNP.out.versions)
        ch_snp_tree = ROOT_TREE_PARSNP.out.tre
    }
    //
    // MODULE: Check that metadata has info for all the samples in the final MSA
    //
    if(params.metadata) {
        CHECK_METADATA_MSA(CLEAN_FASTA.out.cleaned_snps_alignment, file(params.metadata))
        ch_metadata = CHECK_METADATA_MSA.out.metadata
        ch_versions = ch_versions.mix(CHECK_METADATA_MSA.out.versions)}
    else {
        CLEAN_FASTA.out.cleaned_snps_alignment
        .map { meta, _ ->
            def metadata = []
            tuple( meta, metadata)
        }
        .set { ch_metadata }
    }
    //
    // Check if there are previous partitions to keep consistent nomenclature
    //
    CLEAN_FASTA.out.cleaned_snps_alignment
        .map { meta, _ ->
            def prev = get_previous_partitions_tsv(meta.species)
            [ meta, prev ]
        }
        .set { ch_previous_partitions }
    //
    //MODULE: Run ReporTree on the Parsnp results
    //
    REPORTREE_PARSNP(
        CLEAN_FASTA.out.cleaned_snps_alignment,
        ch_metadata,
        ch_previous_partitions
    )
    ch_versions = ch_versions.mix(REPORTREE_PARSNP.out.versions)

    emit:
    dist_hamming        = REPORTREE_PARSNP.out.dist_hamming           //channel: [val (meta), dist_hamming ]
    partitions          = REPORTREE_PARSNP.out.partitions             //channel: [val (meta), partitions_summary]
    dist_tree           = REPORTREE_PARSNP.out.single_HC              //channel: [val(meta), single_hc]
    cluster_composition = REPORTREE_PARSNP.out.cluster_composition    //channel: [val(meta), cluster_composition]
    snp_tree            = ch_snp_tree                                 //channel: [val(meta), tree]
    versions            = ch_versions                                 // channel: [ versions.yml ]
}

/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    THE END
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/
