// TODO nf-core: If in doubt look at other nf-core/subworkflows to see how we are doing things! :)
//               https://github.com/nf-core/modules/tree/master/subworkflows
//               You can also ask for help via your pull request or on the #subworkflows channel on the nf-core Slack workspace:
//               https://nf-co.re/join
// TODO nf-core: A subworkflow SHOULD import at least two modules

include { PARSNP      } from '../../modules/local/parsnp.nf'
include { CLEAN_FASTA } from '../../modules/local/clean_fasta.nf'

workflow PARSNP_ANALYSIS {

    take:
    // TODO nf-core: edit input (take) channels
    ch_samples // channel: [ val(meta), gff, assembly ]
    ch_master_info // channel: [ val(meta), [fastqs], gff, assembly]

    main:

    ch_versions = Channel.empty()

    //Group all the new samples by species and only the assemblies
    ch_samples
        .map {
            meta, gff, assembly ->
            tuple([species:meta.species], assembly)
        }
        .groupTuple()
    .set{ch_new_assemblies}
    //ch_new_assemblies.view()
    //Group all the historic samples by species and only the assemblies
    ch_master_info
        .map {
            meta, fastqs, gff, assembly ->
            tuple([species:meta.species],assembly)
        }
        .groupTuple()
    .set{ch_historic_assemblies}

    //Join the new and historic samples by species
    ch_all_assemblies_per_species = ch_new_assemblies.join(ch_historic_assemblies)
        .map{
            meta, new_assemblies, old_assemblies ->
            [meta,[new_assemblies, old_assemblies].flatten()]
        }
    //ch_all_assemblies_per_species.view()


    //
    //MODULE: Run Parsnp
    //
    PARSNP(
        ch_all_assemblies_per_species
    )

    //
    //MODULE: Clean multi fasta generated by PARSNP
    //
    CLEAN_FASTA(
        PARSNP.out.snps_alingment
    )

    emit:
    // TODO nf-core: edit emitted channels
    // bam      = SAMTOOLS_SORT.out.bam           // channel: [ val(meta), [ bam ] ]
    // bai      = SAMTOOLS_INDEX.out.bai          // channel: [ val(meta), [ bai ] ]
    // csi      = SAMTOOLS_INDEX.out.csi          // channel: [ val(meta), [ csi ] ]

    versions = ch_versions                     // channel: [ versions.yml ]
}

