include { PARSNP                } from '../../modules/local/parsnp.nf'
include { CLEAN_FASTA           } from '../../modules/local/clean_fasta.nf'
include { REPORTREE_PARSNP      } from '../../modules/local/reportree/parsnp.nf'

//Function to get all the previous assembly files for each species
def get_previous_assemblies(species ) {
    // Create the path to get the previous fasta files
    def previous_assemblies = file("${params.previous_results}/${species}/assemblies/*.{fasta,fa,fas}")
    return previous_assemblies
}

workflow PARSNP_ANALYSIS {

    take:
    // TODO nf-core: edit input (take) channels
    ch_samples          // channel: [ val(meta),assembly ]
    ch_parsnp_species   // channel: [[species,count]] //counts included the latest assemblies

    main:

    ch_versions = Channel.empty()

    //For each species get the previous fasta files
    ch_previous_assemblies = Channel.empty()
    ch_previous_assemblies = ch_previous_assemblies.mix(
        ch_parsnp_species.map{
            meta -> [[species:meta[0].species],get_previous_assemblies(meta[0].species)]
        }
    )

    //Group all the samples by species
    ch_samples.map{
        meta, assembly -> [[species:meta.species],assembly]
    }
    .groupTuple()
    .set{ch_samples_grouped_species}

    //Combine the new assemblies and the old assemblies
    ch_all_assemblies = ch_samples_grouped_species.join(ch_previous_assemblies)
        .map{meta,new_assemblies, old_assemblies -> [meta,new_assemblies+old_assemblies]}

    //
    // MODULE: Run Parsnp on each unique species
    //
    PARSNP(
        ch_all_assemblies
    )
    ch_versions = ch_versions.mix(PARSNP.out.versions)

    //
    // MODULE: Clean multi fasta generated by PARSNP
    //
    CLEAN_FASTA(
        PARSNP.out.snps_alingment
    )
    ch_versions = ch_versions.mix(CLEAN_FASTA.out.versions)

    //
    //MODULE: Run ReporTree on the Parsnp results
    //
    REPORTREE_PARSNP(
        CLEAN_FASTA.out.cleaned_snps_alignment
    )
    ch_versions = ch_versions.mix(REPORTREE_PARSNP.out.versions)

    emit:
    dist_hamming        = REPORTREE_PARSNP.out.dist_hamming //channel: [val (meta), results ]
    partitions          = REPORTREE_PARSNP.out.partitions   //channel: [val (meta), partitions_summary]
    dist_tree           = REPORTREE_PARSNP.out.single_HC    //channel: [val(meta), single_hc]
    cluster_composition = REPORTREE_PARSNP.out.cluster_composition //channel: [val(meta), cluster_composition]
    versions = ch_versions                     // channel: [ versions.yml ]
}

