//
//  Remove samples from database and update Parsnp results and ReporTree
//

/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    IMPORT LOCAL MODULES
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/
include { PARSNP                 } from '../../modules/local/parsnp/parsnp.nf'
include { CLEAN_FASTA            } from '../../modules/local/parsnp/clean_fasta.nf'
include { REMOVE_FROM_PARTITIONS } from '../../modules/local/remove_samples/remove_from_partitions.nf'
include { CHECK_METADATA_MSA     } from '../../modules/local/reportree/check_metadata_msa.nf'
include { REPORTREE_PARSNP       } from '../../modules/local/reportree/reportree_parsnp.nf'

/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    RUN MAIN SUBWORKFLOW
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/
workflow REMOVE_PARSNP {

    take:
    samples_to_remove      // channel: [ val(species), val(ids) ]
    updated_assemblies     // channel: [ val(species), path(assemblies) ]
    ch_parsnp_species      // channel: [[species,count]] //counts included the latest assemblies
    outdir                 // file(params.outdir)

    main:

    ch_versions = Channel.empty()

    // Determine which species are allowed to run Parsnp
    ch_allowed_species = ch_parsnp_species
    .filter { it[0].count > 1 }
    .map { species_meta -> tuple(species_meta[0].species, true) }

    ch_parsnp_assemblies = updated_assemblies
        .join(ch_allowed_species)
        .map { species, assemblies, _ ->
            tuple(species, assemblies)
        }

    //
    // MODULE: Run Parsnp on each unique species
    //
    PARSNP(
        ch_parsnp_assemblies
    )
    ch_versions = ch_versions.mix(PARSNP.out.versions)
    //
    // MODULE: Clean multi fasta generated by PARSNP
    //
    CLEAN_FASTA(
        PARSNP.out.snps_alignment
    )
    ch_versions = ch_versions.mix(CLEAN_FASTA.out.versions)
    //
    // MODULE: Check that metadata has info for all the samples in the final MSA
    //
    if(params.metadata) {
        CHECK_METADATA_MSA(CLEAN_FASTA.out.cleaned_snps_alignment, file(params.metadata))
        ch_metadata = CHECK_METADATA_MSA.out.metadata
        ch_versions = ch_versions.mix(CHECK_METADATA_MSA.out.versions)}
    else {
        CLEAN_FASTA.out.cleaned_snps_alignment
        .map { meta, _ ->
            def metadata = []
            tuple( meta, metadata)
        }
        .set { ch_metadata }
    }

    // Join samples to remove
    ch_parsnp_species.map { info ->
    def (species, count) = info
    tuple(species, count)
    }
    .set { schemas_by_species }

    samples_to_remove
    .join(schemas_by_species) // [ species, ids, count, schema ]
    .map { species, ids, count ->
    def meta = [species: species]
    tuple(meta, ids) }
    .set { ch_samples_rm_parsnp } 

    //
    // MODULE: Remove selected samples from partitions
    //
    REMOVE_FROM_PARTITIONS(ch_samples_rm_parsnp,
                            outdir)
    ch_versions = ch_versions.mix(REMOVE_FROM_PARTITIONS.out.versions)

    //
    //MODULE: Run ReporTree on the Parsnp results
    //
    REPORTREE_PARSNP(
        CLEAN_FASTA.out.cleaned_snps_alignment,
        ch_metadata,
        REMOVE_FROM_PARTITIONS.out.partitions
    )
    ch_versions = ch_versions.mix(REPORTREE_PARSNP.out.versions)

    emit:
    dist_hamming        = REPORTREE_PARSNP.out.dist_hamming           //channel: [val (meta), dist_hamming ]
    partitions          = REPORTREE_PARSNP.out.partitions             //channel: [val (meta), partitions_summary]
    dist_tree           = REPORTREE_PARSNP.out.single_HC              //channel: [val(meta), single_hc]
    cluster_composition = REPORTREE_PARSNP.out.cluster_composition    //channel: [val(meta), cluster_composition]
    versions            = ch_versions                                 // channel: [ versions.yml ]
}

/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    THE END
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/
